defmodule SemanticGraph.Repo.Migrations.CreateGraph do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:edges, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:relation_type, :text, null: false)
      add(:certainty, :float, default: 0.5)
      add(:description, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:from_vertex_id, :uuid, null: false)
      add(:to_vertex_id, :uuid, null: false)
    end

    create unique_index(:edges, [:from_vertex_id, :to_vertex_id, :relation_type],
             name: "edges_unique_relationship_index"
           )

    create table(:vertices, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:edges) do
      modify(
        :from_vertex_id,
        references(:vertices,
          column: :id,
          name: "edges_from_vertex_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        )
      )

      modify(
        :to_vertex_id,
        references(:vertices,
          column: :id,
          name: "edges_to_vertex_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        )
      )
    end

    create constraint(:edges, :edges_no_self_loops,
             check: """
               from_vertex_id != to_vertex_id
             """
           )

    alter table(:vertices) do
      add(:content, :text, null: false)
      add(:x, :float, default: 0.0)
      add(:y, :float, default: 0.0)
      add(:group, :bigint, default: 0)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    alter table(:vertices) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:group)
      remove(:y)
      remove(:x)
      remove(:content)
    end

    drop_if_exists(constraint(:edges, :edges_no_self_loops))

    drop(constraint(:edges, "edges_to_vertex_id_fkey"))

    drop(constraint(:edges, "edges_from_vertex_id_fkey"))

    alter table(:edges) do
      modify(:to_vertex_id, :uuid)
      modify(:from_vertex_id, :uuid)
    end

    drop(table(:vertices))

    drop_if_exists(
      unique_index(:edges, [:from_vertex_id, :to_vertex_id, :relation_type],
        name: "edges_unique_relationship_index"
      )
    )

    drop(table(:edges))
  end
end
